FORMAT: 1A

# Carmageddon Back End API - version 1.0.0

The **Carmageddon Back End API** provides access to acquire data
about cities, stations, pumps, and tanks used in the Carmageddon
demonstration scenario.  This API is used by the demonstration client
to obtain information about the corporate resources, their locations,
and processed analytic results.

The base URI for version 1 of the API is:

        http://api.carma.demo.ociweb.com/v1/...

The base URI includes the protocol, hostname and port, and a prefix path
to the endpoint URIs.  The prefix path includes the interface version of
the API being accessed.  Note that any changes to an existing version of
the API will only extend it with additional parameters and endpoints,
allowing existing clients to continue operation without modification when
accessing the API.

<!-- include(api-top-sections.md) -->

# Group City

These resource identifiers represent information about the City resources
of the corporation.  Cities have information about their location and an
intial zoom level when viewing the location on a map.  Each city also has
a name and a state associated with it.  Cities also are a container for
stations; that is each city has a list of stations which are resident in
that city.

## Cities Collection [/cities{?start,span}]

Obtain a list of all cities which have stations owned by the corporation.
This is a paged URI that can be used to obtain the entire set of
information in groups of `span` parameter values.  If no parameters are
supplied, then all cities are returned.  The returned data is an array
of individual city information, not a simple list of `cityid` values.

### List_Cities [GET]

+ Parameters

    + start = `1` (optional,number) ... Numeric index of the first location to return in the response.
    + span = `20` (optional,number) ... Number of City entries to return in the response.

+ Request /cities?start=1&span=4

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/collection.json)

    + Body

           { "data": [ { "id": "c00", "order": "0", "zoom": "4",  "city": "All Cities",   "state": "USA", "lat": "38.4039",    "lon": "-96.1817"},
                       { "id": "c01", "order": "1", "zoom": "9",  "city": "Greenville",   "state": "SC",  "lat": "34.8526176", "lon": "-82.3940104"},
                       { "id": "c02", "order": "2", "zoom": "8",  "city": "Grand Rapids", "state": "MI",  "lat": "42.9633599", "lon": "-85.6680863"},
                       { "id": "c03", "order": "3", "zoom": "10", "city": "Cary",         "state": "NC",  "lat": "39.79154",   "lon": "-78.7811169"}
           ]}

+ Response 204

## Cities Search [/search/cities{?query}]

Search for cities.  This returns a list of cities which meet the criteria
supplied by the `query` parameter.  Search results consist of an array of
individual city information and not just a simple list of `cityid` values.

+ Parameters

    + query (required,string,`state=="MI"`) ... Query parameter for search.

### Search_Cities [GET]

+ Request /search/cities?query=state=="MI"||state=="NC"

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/collection.json)

    + Body

           { "data": [ { "id": "c02", "order": "2", "zoom": "8",  "city": "Grand Rapids", "state": "MI",  "lat": "42.9633599", "lon": "-85.6680863"},
                       { "id": "c03", "order": "3", "zoom": "10", "city": "Cary",         "state": "NC",  "lat": "39.79154",   "lon": "-78.7811169"}
           ]}

+ Response 204

## City [/cities/{cityid}]

Obtain the information for a single city.

### List_single_City [GET]

+ Parameters

    + cityid (required,string,`c03`) ... Unique identfier for the city.

+ Request /cities/c03

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profiile=http://oci-labs.github.io/carma-api/schemas/city.json)

    + Body

           {
             "id": "c03",
             "order": "3",
             "zoom": "10",
             "city": "Cary",
             "state": "NC",
             "lat": "39.79154",
             "lon": "-78.7811169"
           }

+ Response 404

## City Stations [/cities/{cityid}/stations{?start,span}]

City stations are the stations which are located within the city.  The
returned information includes a list of the `stationid` values for
stations which are located within the named city.  Information about the
stations will need to be obtained separately.

+ Parameters

    + cityid (required,string,`c03`) ... Unique identfier for the city.
    + start = `1` (optional,number) ... Numeric index of the first location to return in the response.
    + span = `10` (optional,number) ... Number of City entries to return in the response.

### Get_stations_in_city [GET]

+ Request /cities/c03/stations?start=1&span=4

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/idlist.json)

    + Body

           { "idType": "stations",
             "data": [ "s007",
                       "s008",
                       "s009",
                       "s010"
           ]}

+ Response 204

+ Response 404

# Group Station

These resource identifiers represent information about the Station
resources in the corporation. Each station includes information about
the pumps that are present at that station and the tanks holding the
fuel that is provided by the pumps.  The revenue for a station within
a time period for some or all of the fuel types supplied by a station
can be obtained.  A list of events which have ocurred, or which are
projected to ocurr at a station can be obtained as well.

Events which can occur at a station include the following:

* pumpfail - a pump has been detected as being inoperative at the station
* pumpactive  - a pump is returned to service after being inactive
* pumpinactive  - a pump is removed from service due to scheduled maintenance
* tankfail - a tank has been detected as operating outside of required constraints
* tankactive  - a tank is returned to service within required constraints
* tankinactive  - a tank is removed from service due to scheduled maintenance
* tankfill  - a tank has been filled at the station

## Stations Collection [/stations{?start,span}]

Obtain a list of all stations in the corporation.  This is a paged URI
that can be used to obtain the entire set of information in groups of
`span` parameter values.  If no parameters are supplied, then all
stations are returned.

### List_Stations [GET]

+ Parameters

    + start = `1` (optional,number) ... Numeric index of the first location to return in the response.
    + span = `10` (optional,number) ... Number of Station entries to return in the response.

+ Request /stations?start=1&span=3

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/collection.json)

    + Body

           { "data": [ { "id": "s007", "cityid": "c03", "city": "Cary", "state": "NC", "lat": "35.66029077", "lon": "-79.00755913",
                                       "tanks": { "regular": "t0021", "premium": "t0022", "diesel": "t0023"},
                                       "pumps": ["p0631", "p0849", "p1359", "p1775", "p2589", "p2670", "p3857", "p3927", "p5119", "p5570", "p6126", "p6885"]},
                       { "id": "s008", "cityid": "c03", "city": "Cary", "state": "NC", "lat": "35.5318045", "lon": "-78.92016643",
                                       "tanks": { "regular": "t0024", "premium": "t0025", "diesel": "t0026"},
                                       "pumps": ["p0508", "p1823", "p2123", "p2755", "p4224", "p4636", "p5453", "p6088", "p6831"]},
                       { "id": "s009", "cityid": "c03", "city": "Cary", "state": "NC", "lat": "35.80762049", "lon": "-78.506764",
                                       "tanks": { "regular": "t0027", "premium": "t0028", "diesel": "t0029"},
                                       "pumps": ["p0365", "p0633", "p0944", "p1633", "p2054", "p2518", "p3187", "p3239", "p3682", "p4960", "p5127", "p5959", "p6023", "p6212"]},
           ]}

+ Response 204

## Stations Search [/search/stations{?query}]

Search for stations.  This returns a list of stations which meet the
criteria supplied by the `query` parameter.  Search results consist of an
array of individual station information, not a simple list of `stationid`
values.

### Search_Stations [GET]

+ Parameters

    + query (required,string,`tanks.premium==t0025`) ... Query parameter for search.

+ Request /search/stations?query=tanks.premium=="t0025"

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/collection.json)

    + Body

        { "data": [ { "id": "s008", "cityid": "c03", "city": "Cary", "state": "NC", "lat": "35.5318045", "lon": "-78.92016643",
                                    "tanks": { "regular": "t0024", "premium": "t0025", "diesel": "t0026"},
                                    "pumps": ["p0508", "p1823", "p2123", "p2755", "p4224", "p4636", "p5453", "p6088", "p6831"]}
        ]}

+ Response 204

## Station [/stations/{stationid}]

Obtain the information for a single station.

### List_single_Station [GET]

+ Parameters

    + stationid (required,string,`t0025`) ... Unique identfier for the station.

+ Request /stations/s008

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/station.json)

    + Body

        { "id": "s008",
          "cityid": "c03",
          "city": "Cary",
          "state": "NC",
          "lat": "35.5318045",
          "lon": "-78.92016643",
          "tanks": { "regular": "t0024",
                     "premium": "t0025",
                     "diesel": "t0026"
          },
          "pumps": ["p0508", "p1823", "p2123", "p2755", "p4224", "p4636", "p5453", "p6088", "p6831"]
        }

+ Response 404

## Station Revenue [/stations/{stationid}/revenue{?from,to,fuel}]

Station revenue is the amount of revenue collected from transactions at
all pumps within the station.  The returned information includes the
revenue obtained from the pumps at the station during the supplied
interval.  If no interval is supplied, then all the revenue from the
station is returned.  If the `fuel` parameter is supplied, the the
revenue is reported for each fuel named in the parameter as a separate
value. 

+ Parameters

    + from = `first` (optional,string) ... date string for the start of the period to collect revenue.
    + to = `today` (optional,string) ... date string for the end of the period to collect revenue.
    + fuel = `all` (optional,string) ... selection of one or more fuels to gather revenue amounts for.

### List_Station_Revenue [GET]

+ Request /stations/s007/revenue?from=last%20week&to=today&fuel=diesel

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/revenue.json)

    + Body

        {
          "scope": "station",
          "id": "s007",
          "fuel": "diesel",
          "from": "1440020024",
          "to": "1440624832",
          "amount": "23756.32"
        }

+ Response 204

+ Response 404

## Station Maintenance [/stations/{stationid}/maintenance{?from,to,itemtype}]

Station maintenance actions are records of completed maintenance activity
that was undertaken at a specific station.  This includes maintenance
of all pumps and tanks that are located at the station.  The returned
information includes a list of maintenance actions and the items that
were performed during the supplied interval.  If no interval was supplied
then all maintenance records are returned.  If no `itemtype` parameter
is supplied, then maintenance actions for all item types are returned.

+ Parameters

    + from = `first` (optional,string) ... date string for the start of the period to report maintenance actions .
    + to = `today` (optional,string) ... date string for the end of the period to report maintenance actions.
    + itemtype = `all` (optional,string) ... selection of one or more item types for which maintenance actions are returned.

### List_Station_Maintenance [GET]

+ Request /stations/s007/maintenance?from=last%20week&to=today&itemtype=all

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/maintenance.json)

    + Body

        {
          "scope": "station",
          "id": "s007",
          "maintenance": [
            {"type": "pumpfail", "id": "p0849", "detected": "1440019521", "repaired": "1440278764", "description": "No data received from pump", "action": "Replace sensor"},
            {"type": "tankactive", "id": "t022", "repaired": "1440278764", "description": "scheduled maintenance", "action": "calibrate level sensor"}
          ]
        }

+ Response 204

+ Response 404

## Station Events [/stations/{stationid}/events{?from,to,type}]

Station events are a time series of different event types.  If no `from`
or `to` parameter is supplied, than all events stored for a station are
returned.  If the `type` parameter is supplied, the returned list
provides only the event types included for that parameter.

+ Parameters

    + from = `first` (optional,string) ... date string for the start of the period to report events.
    + to = `today` (optional,string) ... date string for the end of the period to report events.
    + type = `all` (optional,string) ... selection of one or more event types to report events for.

### List_Station_Events [GET]

+ Request /stations/s007/events?from=last%20week&to=today&type=all

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/event.json)

    + Body

        {
          "scope": "station",
          "id": "s007",
          "events": [
            { "type": "pumpfail", "id": "p0849", "when": "1440019521" },
            { "type": "pumpactive", "id": "p0849", "when": "1440278764" },
            { "type": "tankfill", "id": "t0021", "when": "1440392400" },
            { "type": "tankfill", "id": "t0022", "when": "1440392400" },
            { "type": "tankfill", "id": "t0023", "when": "1440392400" }
          ]
        }

+ Response 204

+ Response 404

# Group Pump

These resource identifiers represent information about the pump resources
in the corporation.  Each pump includes information about the fuel types
that it dispenses and can provide the revenue for an interval for some
or all of the fuel types dispensed.  A list of events that have occurred,
or which are projected to occur, can be obtained as well.

Events which can occur at a pump include the following:

* pumpfail - a pump has been detected as being inoperative at the station
* pumpactive  - a pump is returned to service after being inactive
* pumpinactive  - a pump is removed from service due to scheduled maintenance

## Pump Collection [/pumps{?start,span}]

Obtain a list of all the pumps in the corporation.  This is a paged URI
that can be used to obtain the entire set of information in groups of
`span` parameter values.  If no parameters are supplied then all pumps
are returned.  The returned information is an array of individual pump
information, not simple a list of `pumpid` values.

### List_Pumps [GET]

+ Parameters

    + start = `1` (optional,number) ... Numeric index of the first location to return in the response.
    + span = `10` (optional,number) ... Number of Station entries to return in the response.

+ Request /stations?start=1359&span=3

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/collection.json)

    + Body

        { "data": [ { "id": "p1359", "stationid": "s007" },
                    { "id": "p1360", "stationid": "s485" },
                    { "id": "p1361", "stationid": "s043" }
        ]}

+ Response 204

## Pumps Search [/search/pumps{?query}]

Search for pumps.  This returns a list of pumps which meet the criteria
supplied by the `query` parameter.  Search results consist of an array of
individual pump information, not a simple list of `pumpid` values.

### Search_Pumps [GET]

+ Parameters

    + query (required,string,`stationid==s007`) ... Query parameter for search.

+ Request /stations?query=stationid=s007

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/collection.json)

    + Body

        { "data": [ { "id": "p0631", "stationid": "s007" },
                    { "id": "p0849", "stationid": "s007" },
                    { "id": "p1359", "stationid": "s007" },
                    { "id": "p1775", "stationid": "s007" },
                    { "id": "p2589", "stationid": "s007" },
                    { "id": "p2670", "stationid": "s007" },
                    { "id": "p3857", "stationid": "s007" },
                    { "id": "p3927", "stationid": "s007" },
                    { "id": "p5119", "stationid": "s007" },
                    { "id": "p5570", "stationid": "s007" },
                    { "id": "p6126", "stationid": "s007" },
                    { "id": "p6885", "stationid": "s007" }
        ]}

+ Response 204

## Pump [/pumps/{pumpid}]

Obtain the information for a single pump.

### List_single_Pump [GET]

+ Parameters

    + pumpid (required,string,`p1775`) ... Unique identfier for the pump.

+ Request /pumps/p1775

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/pump.json)

    + Body

        { "id": "p1775",
          "stationid": "s007"
        }

+ Response 200

+ Response 404

## Pump Revenue [/pumps/{pumpid}/revenue{?from,to,fuel}]

Pump revenue is the amount of revenue collected from transactions at a
single pump.  The returned information includes the revenue obtained from
the named pump during the supplied interval.  If no interval is supplied,
then all revenue from the pump will be reported.  If the `fuel` parameter
is supplied, then the revenue is reported for each fuel named in the
parameter as a separate value.

### List_Pump_Revenue [GET]

+ Parameters

    + from = `first` (optional,string) ... date string for the start of the period to collect revenue.
    + to = `today` (optional,string) ... date string for the end of the period to collect revenue.
    + fuel = `all` (optional,string) ... selection of one or more fuels to gather revenue amounts for.

+ Request /pumps/p1775/revenue?from=last%20week&to=today&fuel=regular

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/revenue.json)

    + Body

        {
          "scope": "pump",
          "id": "p1775",
          "fuel": "regular",
          "from": "1440020024",
          "to": "1440624832",
          "amount": "2375.25"
        }

+ Response 204

+ Response 404

## Pump Maintenance [/pumps/{pumpid}/maintenance{?from,to}]

Pump maintenance actions are records of completed maintenance activity
that was undertaken for a specific pump.  The returned information
includes a list of maintenance actions and the items that were performed
during the supplied interval.  If no interval was supplied then all
maintenance records are returned.

+ Parameters

    + from = `first` (optional,string) ... date string for the start of the period to report maintenance actions .
    + to = `today` (optional,string) ... date string for the end of the period to report maintenance actions.

### List_Pump_Maintenance [GET]

+ Request /pumps/p0849/maintenance?from=last%20week&to=today

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/maintenance.json)

    + Body

        {
          "scope": "pump",
          "id": "p0849",
          "maintenance": [
            {"type": "pumpfail", "id": "p0849", "detected": "1440019521", "repaired": "1440278764", "description": "No data received from pump", "action": "Replace sensor"}
          ]
        }

+ Response 204

+ Response 404

## Pump Events [/pumps/{pumpid}/events{?from,to,type}]

Pump events are a time series of different event types.  If no `from` or
`to` parameter is supplied then all events stored for a pump are
returned.  If the `type` parameter is supplied the returned list contains
only events of the types included in the parameter value.

### List_Pump_Events [GET]

+ Parameters

    + from = `first` (optional,string) ... date string for the start of the period to report events.
    + to = `today` (optional,string) ... date string for the end of the period to report events.
    + type = `all` (optional,string) ... selection of one or more event types to report events for.

+ Request /pumps/p0849/events?from=last%20week&to=today&type=all

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/event.json)

    + Body

        {
          "scope": "pump",
          "id": "p0849",
          "events": [
            { "type": "pumpfail", "id": "p0849", "when": "1440019521" },
            { "type": "pumpactive", "id": "p0849", "when": "1440278764" }
          ]
        }

+ Response 204

+ Response 404

# Group Tank

These resource identifiers represent information about the tank resources
of the corporation.  Each tank includes information about the fuel type
it holds and its current level.  The tanks size is also included.  A list
of events for a tank can be obtained.  These events can be historical or
future projections.

Events which can occur at a tank include the following:

* tankfail - a tank has been detected as operating outside of required constraints
* tankactive  - a tank is returned to service within required constraints
* tankinactive  - a tank is removed from service due to scheduled maintenance
* tankfill  - a tank has been filled at the station

## Tank Collection [/tanks{?start,span}]

Obtain a list of all tanks in the corporation.  This is a paged URI that
can be used to obtain the entire set of information in groups of `span`
parameter values.  If no parameters are supplied, then all tanks are
returned.

### List_Tanks [GET]

+ Parameters

    + start = `1` (optional,number) ... Numeric index of the first location to return in the response.
    + span = `10` (optional,number) ... Number of Station entries to return in the response.

+ Request /tanks?start=21&span=3

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/collection.json)

    + Body

        { "data": [ { "id": "t0021", "stationid": "s007", "fuel": "regular", "capacity": "20000" },
                    { "id": "t0022", "stationid": "s007", "fuel": "premium", "capacity": "20000" },
                    { "id": "t0023", "stationid": "s007", "fuel": "diesel",  "capacity": "16000" }
        ]}

+ Response 200

+ Response 204

## Tanks Search [/search/tanks{?query}]

Search for tanks.  This returns a list of tanks which meet the criteria
supplied by the `query` parameter.  Search results consist of an array of
individual tank information, not a simple list of `tankid` values.

### Search_Tanks [GET]

+ Parameters

    + query (required,string,`stationid=="s007"&&fuel=="diesel"`) ... Query parameter for search.

+ Request /search/tanks?query=id==t0022

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/collection.json)

    + Body

        { "data": [ { "id": "t0022", "stationid": "s007", "fuel": "premium", "capacity": "20000" }
        ]}

+ Response 204

## Tank [/tanks/{tankid}]

Obtain the information for a single tank.

### Get_tank [GET]

+ Parameters

    + tankid (required,string,`t0022`) ... Unique identfier for the tank.

+ Request /tanks/t0022

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/tank.json)

    + Body

        { "id": "t0022",
          "stationid": "s007",
          "fuel": "premium",
          "capacity": "20000"
        },

+ Response 404

## Tank Maintenance [/tanks/{tankid}/maintenance{?from,to}]

Tank maintenance actions are records of completed maintenance activity
that was undertaken for a specific tank.  The returned information
includes a list of maintenance actions and the items that were performed
during the supplied interval.  If no interval was supplied then all
maintenance records are returned.

+ Parameters

    + from = `first` (optional,string) ... date string for the start of the period to report maintenance actions .
    + to = `today` (optional,string) ... date string for the end of the period to report maintenance actions.

### List_Tank_Maintenance [GET]

+ Request /tanks/t022/maintenance?from=last%20week&to=today

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/maintenance.json)

    + Body

        {
          "scope": "tank",
          "id": "t022",
          "maintenance": [
            {"type": "tankactive", "id": "t022", "repaired": "1440278764", "description": "scheduled maintenance", "action": "calibrate level sensor"}
          ]
        }

+ Response 204

+ Response 404

## Tank Events [/tanks/{tankid}/events{?from,to,type}]

Tank events are a time series of different event types.  If no `from` or
`to` parameter is supplied, then all events stored for a tank are
returned.  If the `type` parameter is supplied, the returned list
provides only the event types included for that parameter.

### List_Tank_Events [GET]

+ Parameters

    + from = `first` (optional,string) ... date string for the start of the period to report events.
    + to = `today` (optional,string) ... date string for the end of the period to report events.
    + type = `all` (optional,string) ... selection of one or more event types to report events for.

+ Request /tanks/t0022/events?from=last%20week&to=today&type=all

+ Response 200 (application/prs.com.ociweb.demo.carma+json; profile=http://oci-labs.github.io/carma-api/schemas/event.json)

    + Body

        {
          "scope": "tank",
          "id": "t0022",
          "events": [
            { "type": "tankfill", "id": "t0022", "when": "1440392400" }
          ]
        }

+ Response 204

+ Response 404

